In [1]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn import datasets

In [2]:
lfw=datasets.fetch_lfw_people(min_faces_per_person=100,resize=0.4)

ImportError: The Python Imaging Library (PIL) is required to load data from jpeg files

In [ ]:
lfw.keys()

In [ ]:
lfw.data.shape

In [ ]:
lfw.images.shape

In [ ]:
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier

In [ ]:
fig=plt.figure(figsize=(8,8))
for i in range(64):
  ax=fig.add_subplot(8,8,i+1)
  ax.imshow(lfw.images[i],cmap=plt.cm.bone)
plt.show()  

In [0]:
xtrain,xtest,ytrain,ytest=train_test_split(lfw.data,lfw.target)

In [0]:
pca=PCA()
xtrain_pca=pca.fit(xtrain)


In [34]:
k=0
current_var=0
total=sum(pca.explained_variance_)

while current_var/total<=0.99:
  current_var += pca.explained_variance_[k]
  k=k+ 1
k  

112

In [0]:
pca=PCA(n_components=k,whiten=True)

xtrain_pca=pca.fit_transform(xtrain)
xtest_pca=pca.transform(xtest)

In [36]:
rf=RandomForestClassifier()
rf.fit(xtrain,ytrain)
ypred=rf.predict(xtest)
print(classification_report(ytest,ypred))
print(confusion_matrix(ytest,ypred))

             precision    recall  f1-score   support

          0       0.67      0.71      0.69        62
          1       0.30      0.29      0.30        24
          2       0.60      0.83      0.69       126
          3       0.70      0.20      0.31        35
          4       0.83      0.26      0.40        38

avg / total       0.63      0.60      0.57       285

[[ 44   2  16   0   0]
 [  4   7  13   0   0]
 [ 11   7 104   2   2]
 [  2   3  23   7   0]
 [  5   4  18   1  10]]


In [37]:
rf.fit(xtrain_pca,ytrain)
ypred_pca=rf.predict(xtest_pca)
print(classification_report(ytest,ypred_pca))
print(confusion_matrix(ytest,ypred_pca))

             precision    recall  f1-score   support

          0       0.53      0.53      0.53        62
          1       0.43      0.25      0.32        24
          2       0.58      0.86      0.69       126
          3       0.56      0.14      0.23        35
          4       0.73      0.29      0.42        38

avg / total       0.58      0.57      0.53       285

[[ 33   3  23   2   1]
 [  1   6  16   1   0]
 [ 15   2 108   0   1]
 [  5   1  22   5   2]
 [  8   2  16   1  11]]


In [0]:
from sklearn.svm import SVC

In [54]:
svm=SVC(C=100)
svm.fit(xtrain,ytrain)
ypred_svm=svm.predict(xtest)
print(classification_report(ytest,ypred_svm))
print(confusion_matrix(ytest,ypred_svm))

             precision    recall  f1-score   support

          0       0.00      0.00      0.00        62
          1       0.00      0.00      0.00        24
          2       0.44      1.00      0.61       126
          3       0.00      0.00      0.00        35
          4       0.00      0.00      0.00        38

avg / total       0.20      0.44      0.27       285

[[  0   0  62   0   0]
 [  0   0  24   0   0]
 [  0   0 126   0   0]
 [  0   0  35   0   0]
 [  0   0  38   0   0]]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [55]:
svm.fit(xtrain_pca,ytrain)
ypred_svm_pca=svm.predict(xtest_pca)
print(classification_report(ytest,ypred_svm_pca))
print(confusion_matrix(ytest,ypred_svm_pca))

             precision    recall  f1-score   support

          0       0.95      0.90      0.93        62
          1       0.95      0.83      0.89        24
          2       0.84      0.98      0.91       126
          3       0.96      0.63      0.76        35
          4       0.91      0.82      0.86        38

avg / total       0.90      0.89      0.88       285

[[ 56   1   5   0   0]
 [  0  20   3   1   0]
 [  2   0 124   0   0]
 [  1   0   9  22   3]
 [  0   0   7   0  31]]


In [0]:
from sklearn.model_selection import GridSearchCV
from math import e

In [57]:
grid={'C':[1e2,1e3,1e4,1e5,3e2,5e4]}
abc=GridSearchCV(svm,grid)
abc.fit(xtrain_pca,ytrain)
abc.best_estimator_

SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)